server {
    listen      96;
    listen [::]:96;

    gzip on;
    gunzip on;
    gzip_static on;
    gzip_types text/plain application/xml;
    gzip_min_length 1000;

    location / {
        root /project/nadin-timer;
         # First attempt to serve request as file, then
        # as directory, then redirect to index(angular) if no file found.
        try_files $uri $uri/ /index.html;
    }

}
